### ISSUE TITLE
Covert the Error Log Page to Search w/Pagination

### ISSUE THREAD

**Issue by Barbarrosa** [leebradley/wikiedit-monitor#11]
The error log page that's available via `lookup.js` becomes bulky and slow as data accumulates in the database. We need to add the ability to filter the error log via search and to allow pagination on the initial page and after applying a search filter.

**Comment by ameliabradley** [comment]
From the other night, here's the library we're considering using:
https://www.datatables.net/examples/data_sources/server_side.html

Examples with AJAX-sourced data:
https://www.datatables.net/examples/ajax/

**Comment by ameliabradley** [comment]
Added
